flutter_icons:
  android: "ic_launcher"
  image_path: "assets/img/logo_white.png"
  image_path_ios: "assets/img/logo_white.png"
  adaptive_icon_foreground: "assets/img/logo_white.png"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#454F63"


## flutter pub run flutter_launcher_icons:main -f config/icon_flutter_launcher_icons.yaml